[project]
name = "stream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "streamlit-authenticator>=0.4.2",
    "streamlit-option-menu>=0.4.0",
]
